stages:
  - install
  - build
  - test

.node_modules_cache:
  cache:
    key: '$CI_COMMIT_REF_SLUG.node_modules'
    paths:
      - node_modules/

.node_modules_cache_pull:
  extends: .node_modules_cache
  cache:
    policy: pull

install:
  extends: .node_modules_cache
  stage: install
  script:
    - yarn install

build-makeflow-e2e:
  extends: .node_modules_cache_pull
  stage: build

build-makeflow-web:
  extends: .node_modules_cache_pull
  stage: build
  script:
    - ./scripts/build-dependencies.js

test:
  stage: test
