stages:
  - test

test:
  stage: test
  script:
    - docker-compose up --build --force-recreate --remove-orphans --renew-anon-volumes --exit-code-from test
  only:
    variables:
      - $TEST_PROJECT
